//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payrellunrwa.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name="رقم الموظف")]
        public int Id { get; set; }
        [DisplayName("اسم الموظف ")]
        public string Name { get; set; }
        [DisplayName("الراتب")]
        public Nullable<int> Salary { get; set; }
        [DisplayName("تاريخ الميلاد")]

        public Nullable<System.DateTime> DOB { get; set; }
    }
}
