//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payrellunrwa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salary
    {
        [Display(Name = "رقم متسلسل")]
        public int SalaryID { get; set; }
        [Display(Name = "رقم الموظف")]
        public Nullable<int> EmpId { get; set; }
        [Display(Name = "الشهر ")]
        public string Month { get; set; }
        [Display(Name = "السنه ")]
        public Nullable<int> Year { get; set; }
        [Display(Name = "الراتب الاساسي ")]
        public int Basic_Salary { get; set; }
        [Display(Name = "الخصم ")]
        public Nullable<int> Discount { get; set; }
        [Display(Name = "العلاوه ")]
        public Nullable<int> Bonus { get; set; }
        [Display(Name = "الاضافي ")]
        public Nullable<int> Overtime { get; set; }

        [Display(Name = "عقوبات جزائيه  ")]
        public Nullable<int> Penalties { get; set; }
        [Display(Name = "صافي الراتب ")]

        public Nullable<int> Penatlies_days { get; set; }
       // [Display(Name = "عقوبات جزائيه ")]

    }
}
